### ISSUE TITLE
Running on Heroku

### ISSUE THREAD

**Issue by draganbabic** [jimkang/slack-gis#1]
Hey man, I would love to be able to run this on Heroku, but when I do `heroku run make install` I get the following error: 

```
heroku run make install
Running make install on slack-gis... up, run.7996
make: *** No rule to make target `install'.  Stop.
```

The app deploys fine, but doesn't work in Slack. 

Appreciate any help you can send my way. Thanks!

**Comment by jimkang** [comment]
There definitely is no `install` target in the Makefile. I haven't used Heroku in a while, but all you should have to is run `npm install` and then `node slack-gis.js`. Maybe via `heroku run npm install` and `heroku run node slack-gis.js`?

**Comment by draganbabic** [comment]
I think that did the trick, and I got the following message: 

```
The slack-gis webhook server is running.
Webhook server listening at port: 7778
```

However the command still does nothing in Slack…

**Comment by jimkang** [comment]
OK, so things are running on your Heroku dynamo. There just seems to be a problem getting to it from the outside.
1. Did you [set up the outgoing webhook in Slack](https://github.com/jimkang/slack-gis#running-it-yourself-on-linux-or-mac-probably-the-same-for-windows-but-i-havent-tried-it) and include the port in the URL?
2. Can you get a response from the server outside of Slack? You can try POSTing from curl like this:
   
   curl --data "token=<THE TOKEN YOU PUT IN CONFIG.JS GOES HERE>&user_id=U2147483697&user_name=Steve&text=cats" http://YOUR-APP.heroku.com:7778

If things are working, you should get a response like this:

```
{"username":"google-image-search","text":"https://i.ytimg.com/vi/UIrEM_9qvZU/maxresdefault.jpg"}
```

**Comment by draganbabic** [comment]
Yeah, I set up the outgoing webhook, all should be fine there.

I am getting a connection refused error on cURL, so it's definitely not
working.

I don't want to waste too much of your time, so I'm dropping it now. Thanks
for your help so far!

On Wed, Dec 9, 2015 at 4:07 PM jimkang notifications@github.com wrote:

> OK, so things are running on your Heroku dynamo. There just seems to be a
> problem getting to it from the outside.
> 
>    1.
> 
>    Did you set up the outgoing webhook in Slack
>    https://github.com/jimkang/slack-gis#running-it-yourself-on-linux-or-mac-probably-the-same-for-windows-but-i-havent-tried-it
>    and include the port in the URL?
>    2.
> 
>    Can you get a response from the server outside of Slack? You can try
>    POSTing from curl like this:
> 
>    curl --data "token=<THE TOKEN YOU PUT IN CONFIG.JS GOES
>    HERE>&user_id=U2147483697&user_name=Steve&text=cats"
>    http://YOUR-APP.heroku.com:7778
> 
> If things are working, you should get a response like this:
> 
> {"username":"google-image-search","text":"https://i.ytimg.com/vi/UIrEM_9qvZU/maxresdefault.jpg"}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jimkang/slack-gis/issues/1#issuecomment-163283968.
> 
> ## 

There's a possibility that this is typed on a glass screen. If so, I'm srry
for the typos and brevity.

Dragan.

**Comment by jimkang** [comment]
OK, I don't mind helping, though! Feel free to reopen the issue if you'd like.

BTW, one possibility is that Heroku maps internal ports to different external ports. e.g. 7778 => 5000
