### ISSUE TITLE
slack-gis acting up lately?

### ISSUE THREAD

**Issue by boltar** [jimkang/slack-gis#2]
I'm seeing image retrievals fail recently, and it's intermittent. Have you noticed anything on your end? 

> pr 07 11:20:09 poundc-gis app/web.1:  /app/node_modules/g-i-s/index.js:38 
> Apr 07 11:20:09 poundc-gis app/web.1:    var imageURL = gisURL.replace(gisPrefixRegex, ''); 
> Apr 07 11:20:09 poundc-gis app/web.1:                         ^ 
> Apr 07 11:20:09 poundc-gis app/web.1:  TypeError: Cannot read property 'replace' of undefined 
> Apr 07 11:20:09 poundc-gis app/web.1:      at getImageURLFromGISURL (/app/node_modules/g-i-s/index.js:38:24) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at Array.map (native) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at Request.parseGISResponse [as _callback](/app/node_modules/g-i-s/index.js:28:27) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at Request.self.callback (/app/node_modules/g-i-s/node_modules/request/request.js:198:22) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at emitTwo (events.js:87:13) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at Request.emit (events.js:172:7) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at Request.<anonymous> (/app/node_modules/g-i-s/node_modules/request/request.js:1035:10) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at emitOne (events.js:82:20) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at Request.emit (events.js:169:7) 
> Apr 07 11:20:09 poundc-gis app/web.1:      at IncomingMessage.<anonymous> (/app/node_modules/g-i-s/node_modules/request/request.js:962:12)

**Comment by jimkang** [comment]
I think Google image search result pages have changed in a way that the scraper can't deal with. I'll take a look tonight!

**Comment by jimkang** [comment]
OK, I updated this yesterday with the fix. A change was needed to the scraper to handle a page format change: https://github.com/jimkang/g-i-s

**Comment by boltar** [comment]
thanks, works great!
